language: node_js

node_js:
  - "7"
  - "8"

env:
  global:
    - NODE_ENV=test
    - MONGODB_URI=mongodb://localhost/service

before_script:
  - "cd client"
  - "npm install"
  - "cd .."
  - "cd server"
  - "npm install"

script:
  - npm run coveralls

after_success:
  - bash <(curl -s https://codecov.io/bash)

services: mongodb
