# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Marcin Mrotek

# Copy custom configuration file from the current directory
COPY nginx.custom.conf /etc/nginx/nginx.custom.conf
